const Sequelize = require('sequelize');

const sequelize = require('../util/database');

const RoofCalc = sequelize.define('roofcalc', {
    id: { type: Sequelize.INTEGER, autoIncrement: true, allowNull: false, primaryKey: true },
    adjPipeVents: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    bVent: { type: Sequelize.INTEGER, defaultValue: 0 },
    bvSize: { type: Sequelize.STRING, defaultValue: "N/A" },
    caulk: { type: Sequelize.INTEGER, defaultValue: 0 },
    cNail: { type: Sequelize.INTEGER, defaultValue: 0 },
    deck: { type: Sequelize.INTEGER, defaultValue: 0 },
    desc1: { type: Sequelize.STRING, defaultValue: "N/A" },
    desc2: { type: Sequelize.STRING, defaultValue: "N/A" },
    desc3: { type: Sequelize.STRING, defaultValue: "N/A" },
    desc4: { type: Sequelize.STRING, defaultValue: "N/A" },
    drip24: { type: Sequelize.INTEGER, defaultValue: 0 },
    dripColor: { type: Sequelize.STRING, defaultValue: "N/A" },
    dripEdge: { type: Sequelize.INTEGER, defaultValue: 0 },
    dripSize: { type: Sequelize.STRING, defaultValue: "N/A" },
    eaveStarter: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    felt: { type: Sequelize.INTEGER, defaultValue: 0 },
    feltWgt: { type: Sequelize.STRING, defaultValue: "N/A" },
    flashing: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    hip: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    hipRidge: { type: Sequelize.INTEGER, defaultValue: 0 },
    iceWater: { type: Sequelize.INTEGER, defaultValue: 0 },
    lFlash: { type: Sequelize.INTEGER, defaultValue: 0 },
    modBase: { type: Sequelize.INTEGER, defaultValue: 0 },
    needDeck: { type: Sequelize.STRING, defaultValue: "N/A" },
    noIWCourses: { type: Sequelize.INTEGER, defaultValue: 0 },
    orderNotes: Sequelize.STRING,
    other1: { type: Sequelize.INTEGER, defaultValue: 0 },
    other2: { type: Sequelize.INTEGER, defaultValue: 0 },
    other3: { type: Sequelize.INTEGER, defaultValue: 0 },
    other4: { type: Sequelize.INTEGER, defaultValue: 0 },
    pNail: { type: Sequelize.INTEGER, defaultValue: 0 },
    rake: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    ridge: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    rollRoof: { type: Sequelize.INTEGER, defaultValue: 0 },
    rollValley: { type: Sequelize.INTEGER, defaultValue: 0 },
    sColor: { type: Sequelize.STRING, defaultValue: "N/A" },
    sFlash: { type: Sequelize.INTEGER, defaultValue: 0 },
    shingles: { type: Sequelize.INTEGER, defaultValue: 0 },
    sManufacturer: { type: Sequelize.STRING, defaultValue: "N/A" },
    sMaterial: { type: Sequelize.STRING, defaultValue: "N/A" },
    sName: { type: Sequelize.STRING, defaultValue: "N/A" },
    sprayPaint: { type: Sequelize.INTEGER, defaultValue: 0 },
    sprayPrimer: { type: Sequelize.INTEGER, defaultValue: 0 },
    squares: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    starter: { type: Sequelize.INTEGER, defaultValue: 0 },
    stepFlashing: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    supplier: { type: Sequelize.STRING, defaultValue: "N/A" },
    tinShingles: { type: Sequelize.INTEGER, defaultValue: 0 },
    totalArea: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    turtleColor: { type: Sequelize.STRING, defaultValue: "N/A" },
    turtleVents: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    unit1: { type: Sequelize.STRING, defaultValue: "N/A" },
    unit2: { type: Sequelize.STRING, defaultValue: "N/A" },
    unit3: { type: Sequelize.STRING, defaultValue: "N/A" },
    unit4: { type: Sequelize.STRING, defaultValue: "N/A" },
    valley: { type: Sequelize.FLOAT(10, 2), defaultValue: 0.00 },
    vcSize: { type: Sequelize.STRING, defaultValue: "N/A" },
    versaCaps: { type: Sequelize.INTEGER, defaultValue: 0 },

});

module.exports = RoofCalc;